version: '2'
services:
  mydt:
    image: "mcchae/xfce"
    hostname: "mydt"
    ports:
      - "33899:3389"
      - "60811:6081"
    volumes:
      - ${HOME}/dhv/toor:/home/toor
      - ${HOME}/work:/home/toor/work
